services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wtf.rent
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
  redis:
    image: redis:8
    restart: unless-stopped
    environment:
      - REDIS_ARGS=--appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
