allowBuilds:
  "@parcel/watcher": true
  esbuild: true

minimumReleaseAgeExclude:
  - "@remix-run/assets@0.5.0"
  - "@remix-run/async-context-middleware@0.3.5"
  - "@remix-run/auth-middleware@0.2.5"
  - "@remix-run/auth@0.2.7"
  - "@remix-run/cli@0.4.0 || 0.5.0"
  - "@remix-run/compression-middleware@0.1.13"
  - "@remix-run/cookie@0.6.0"
  - "@remix-run/cop-middleware@0.1.8"
  - "@remix-run/cors-middleware@0.1.8"
  - "@remix-run/csrf-middleware@0.1.8"
  - "@remix-run/data-table-mysql@0.5.0"
  - "@remix-run/data-table-postgres@0.5.0"
  - "@remix-run/data-table-sqlite@0.6.0"
  - "@remix-run/data-table@0.4.0"
  - "@remix-run/fetch-proxy@0.8.5"
  - "@remix-run/fetch-router@0.21.0"
  - "@remix-run/form-data-middleware@0.3.5"
  - "@remix-run/form-data-parser@0.17.5"
  - "@remix-run/logger-middleware@0.3.5"
  - "@remix-run/method-override-middleware@0.1.13"
  - "@remix-run/multipart-parser@0.16.4"
  - "@remix-run/node-fetch-server@0.14.1"
  - "@remix-run/node-hmr@0.1.0"
  - "@remix-run/render-middleware@0.1.5"
  - "@remix-run/response@0.3.8"
  - "@remix-run/route-pattern@0.24.0"
  - "@remix-run/session-middleware@0.4.0"
  - "@remix-run/test@0.6.0"
  - "@remix-run/ui-hmr@0.1.0"
  - "@remix-run/ui@0.5.0 || 0.7.0"
  - remix@3.0.0-beta.6 || 3.0.0-beta.10
  - "@remix-run/static-middleware@0.4.14"
namedRegistries:
  npmjs: https://npm-proxy.mcansh.workers.dev/
registry: https://npm-proxy.mcansh.workers.dev/
